### ISSUE TITLE
Kiosk UI: Coupon issue

### ISSUE THREAD

**Issue by Non-J** [cs350-team4/ats#28]
- [x] Component to display individual item
- [x] Component to list all items (waiting for #9)
- [x] Backend connection to issue coupons (waiting for #7)
- [x] Display number of tickets (waiting for #7)
- [x] Login and logout

**Comment by KalasLavas** [comment]
Note: `/user/coupon-issue` is replaced by `/coupon/issue` (#30)
