### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by m-spitfire** [cs350-team4/ats#4]
- [ ] Handle JWT header on requests to find user and their class
- [x] Generate JWT token: `/auth/generateToken`
- [x] Fetch public key from server @KalasLavas
